version: "3.8"

services:

  mongodb-container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  back-end:
    build: ./back-end
    env_file:
      - ./back-end/.env
    ports:
      - "8082:8082"
    volumes:
      - ./back-end:/app
    depends_on:
      - mongodb-container

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - back-end

  front-end:
    build: ./front-end
    env_file:
      - ./front-end/.env
    ports:
      - "4100:4100"
    volumes:
      - ./front-end:/app
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - back-end

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mongo-data:
  mongo-config:
  prometheus_data:
